_BASE_: ../Base-AGW.yml

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)
  CAMSTYLE: True

MODEL:
  LOSSES:
    CE:
      CAMSTYLE_SCALE: 0.5

OUTPUT_DIR: logs/market1501/agw_R50_camstyle_scale
